FROM wordpress:latest

# install wp-cli
RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && chmod +x wp-cli.phar && mv wp-cli.phar /usr/local/bin/wp

ADD mu-plugins /var/www/html/wp-content/mu-plugins
ADD themes /var/www/html/wp-content/themes

COPY custom.ini $PHP_INI_DIR/conf.d/

