version: '3.7'

services:
  db:
    # If you really want to use MySQL, uncomment the following line
    image: mysql:latest
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
      - ./data:/docker-entrypoint-initdb.d
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    expose:
      - 3306
      - 33060

  wordpress:
    container_name: wordpress
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./themes/picostrap5:/var/www/html/wp-content/themes/picostrap5
      - ./themes/picostrap5-child-base:/var/www/html/wp-content/themes/picostrap5-child-base
      - ./mu-plugins:/var/www/html/wp-content/mu-plugins
      - uploads:/var/www/html/wp-content/uploads
    ports:
      - 8000:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
      - PHP_INI_UPLOAD_MAX_FILESIZE=64M  # Adjust the value as needed

volumes:
  db_data:
  uploads:
